<a href="https://colab.research.google.com/github/harakenken22/diveintocode-ml/blob/master/Sprint22_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sprintの目的
---
スクラッチを通してリカレントニューラルネットワークの基礎を理解する

- どのように学ぶか

スクラッチでリカレントニューラルネットワークの実装を行います。

- リカレントニューラルネットワークスクラッチ

リカレントニューラルネットワーク（RNN） のクラスをスクラッチで作成していきます。NumPyなど最低限のライブラリのみを使いアルゴリズムを実装していきます。

フォワードプロパゲーションの実装を必須課題とし、バックプロパゲーションの実装はアドバンス課題とします。

クラスの名前はScratchSimpleRNNClassifierとしてください。クラスの構造などは以前のSprintで作成したScratchDeepNeuralNetrowkClassifierを参考にしてください。

[DIVER](https://diver.diveintocode.jp/curriculums/1982)

【問題1】SimpleRNNのフォワードプロパゲーション実装
---
SimpleRNNのクラスSimpleRNNを作成してください。基本構造はFCクラスと同じになります。

フォワードプロパゲーションの数式は以下のようになります。ndarrayのshapeがどうなるかを併記しています。

バッチサイズをbatch_size、入力の特徴量数をn_features、RNNのノード数をn_nodesとして表記します。活性化関数はtanhとして進めますが、これまでのニューラルネットワーク同様にReLUなどに置き換えられます。

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
class Tanh():
  """
  活性化関数定義：ハイパボリックタンジェント
  """

  def __init__(self):
    pass

  def forward(self, A):
    self.A = A
    self.Z = np.tanh(self.A)
    return self.Z

  def backward(self, dZ):
    return dZ*(1-self.Z**2)

In [78]:
class SimpleInitializer:
  def Wx(self, n_nodes1, n_nodes2):
    """
    重みの初期化
    Parameters
    ----------
    n_nodes1 : int
      前の層のノード数
    n_nodes2 : int
      後の層のノード数

    Returns
    ----------
    W : 重み
    """
    Wx = np.array([[1,3,5,7], [3,5,7,8]])/100
    return Wx

  def Wh(self, n_nodes1, n_nodes2):
         
    Wh = np.array([[1,3,5,7],
                   [2,4,6,8],
                   [3,5,7,8],
                   [4,6,8,10]])/100
    return Wh
    
  def B(self, n_nodaes2):
    """
    バイアスの初期化
    Parameters
    ----------
    n_nodes2 : int
      後の層のノード数

    Returns
    ----------
    B : バイアス
    """
    #np.zeros(n_nodes2)
    B = np.array([1,1,1,1])
    return B

$
a_t = x_{t}\cdot W_{x} + h_{t-1}\cdot W_{h} + B\\
h_t = tanh(a_t)
$

In [107]:
class FC:
  def __init__(self, n_batch, input_nodes, output_nodes, initializer, activation):
      self.n_batch = n_batch
      self.input_nodes = input_nodes
      self.output_nodes = output_nodes
      self.initializer = initializer
      self.activation = activation
        
        # 初期化
        # initializerのメソッドで、self.Wx,self.Wh,self.Bを初期化する
        
      self.Wx = self.initializer.Wx(self.input_nodes, self.output_nodes)
      self.Wh = self.initializer.Wh(self.output_nodes, self.output_nodes)
      self.B = self.initializer.B(self.output_nodes)
        
      self.H = np.zeros([self.n_batch, self.output_nodes])



  def forward(self, X):

        #上記の式Aを作成
      self.X = X
      print('X:{}'.format(self.X))
      self.A = np.dot(self.X, self.Wx) + np.dot(self.H, self.Wh) + self.B
      print('A:{}'.format(self.A))
      print('Wx:{}'.format(self.Wx))
      print('Wh:{}'.format(self.Wh))
     

      self.H = self.activation.forward(self.A)
      print('H:{}'.format(self.H))

      return self.H

In [113]:
class ScratchSimpleRNNClassifier:
  def __init__(self, n_nodes):
    """
        Parameters
        ----------
        """
    self.n_nodes = n_nodes
  
  def fit(self, X):
      self.n_batch = X.shape[0]
      self.n_features = X.shape[2]
      initializer = SimpleInitializer()
      #インスタンス化して別のクラスにわたす(initializer, Tanh())
      affine = FC(self.n_batch, self.n_features, self.n_nodes, initializer, Tanh())
      
      for t in range(X.shape[1]):
        h = affine.forward(X[:, t, :])
        print('h.shape{}'.format(h.shape))

      return h 


In [114]:
x = np.array([[[1, 2], [2, 3], [3, 4]]])/100 # (batch_size, n_sequences, n_features)
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]])/100 # (n_features, n_nodes)
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]])/100 # (n_nodes, n_nodes)
batch_size = x.shape[0] # 1
n_sequences = x.shape[1] # 3
n_features = x.shape[2] # 2
n_nodes = w_x.shape[1] # 4

h = np.zeros((batch_size, n_nodes)) # (batch_size, n_nodes)
b = np.array([1, 1, 1, 1]) # (n_nodes,)

In [115]:
print (x.shape)
print (w_x.shape)
print (w_h.shape)
print (b.shape)

(1, 3, 2)
(2, 4)
(4, 4)
(4,)


In [116]:
# RNN = ScratchSimpleRNNClassifier(n_nodes)

In [120]:
# RNN.fit(x)

#####下記は、関数の理解のために実装

In [106]:
n_batch = x.shape[0]
print(n_batch)
n_features = x.shape[2]
print(n_features)

initializer = SimpleInitializer()
#インスタンス化して別のクラスにわたす(initializer, Tanh())

affine = FC(n_batch, n_features, n_nodes, initializer, Tanh())
print(affine.forward)

for t in range(x.shape[1]):
  h = affine.forward(x[:, t, :])
print(h)

1
2
<bound method FC.forward of <__main__.FC object at 0x7f8efb0eb8d0>>
X:[[0.01 0.02]]
Wx:[[0.01 0.03 0.05 0.07]
 [0.03 0.05 0.07 0.08]]
Wh:[[0.01 0.03 0.05 0.07]
 [0.02 0.04 0.06 0.08]
 [0.03 0.05 0.07 0.08]
 [0.04 0.06 0.08 0.1 ]]
H:[[0.76188798 0.76213958 0.76239095 0.76255841]]
X:[[0.02 0.03]]
Wx:[[0.01 0.03 0.05 0.07]
 [0.03 0.05 0.07 0.08]]
Wh:[[0.01 0.03 0.05 0.07]
 [0.02 0.04 0.06 0.08]
 [0.03 0.05 0.07 0.08]
 [0.04 0.06 0.08 0.1 ]]
H:[[0.792209   0.8141834  0.83404912 0.84977719]]
X:[[0.03 0.04]]
Wx:[[0.01 0.03 0.05 0.07]
 [0.03 0.05 0.07 0.08]]
Wh:[[0.01 0.03 0.05 0.07]
 [0.02 0.04 0.06 0.08]
 [0.03 0.05 0.07 0.08]
 [0.04 0.06 0.08 0.1 ]]
H:[[0.79494228 0.81839002 0.83939649 0.85584174]]
[[0.79494228 0.81839002 0.83939649 0.85584174]]


### 【問題2】小さな配列でのフォワードプロパゲーションの実験
小さな配列でフォワードプロパゲーションを考えてみます。

入力x、初期状態h、重みw_xとw_h、バイアスbを次のようにします。

ここで配列xの軸はバッチサイズ、系列数、特徴量数の順番です。

In [121]:
RNN = ScratchSimpleRNNClassifier(n_nodes)
RNN.fit(x)

X:[[0.01 0.02]]
A:[[1.0007 1.0013 1.0019 1.0023]]
Wx:[[0.01 0.03 0.05 0.07]
 [0.03 0.05 0.07 0.08]]
Wh:[[0.01 0.03 0.05 0.07]
 [0.02 0.04 0.06 0.08]
 [0.03 0.05 0.07 0.08]
 [0.04 0.06 0.08 0.1 ]]
H:[[0.76188798 0.76213958 0.76239095 0.76255841]]
h.shape(1, 4)
X:[[0.02 0.03]]
A:[[1.07733574 1.13931527 1.20129481 1.25535044]]
Wx:[[0.01 0.03 0.05 0.07]
 [0.03 0.05 0.07 0.08]]
Wh:[[0.01 0.03 0.05 0.07]
 [0.02 0.04 0.06 0.08]
 [0.03 0.05 0.07 0.08]
 [0.04 0.06 0.08 0.1 ]]
H:[[0.792209   0.8141834  0.83404912 0.84977719]]
h.shape(1, 4)
X:[[0.03 0.04]]
A:[[1.08471832 1.15192269 1.21912707 1.27759095]]
Wx:[[0.01 0.03 0.05 0.07]
 [0.03 0.05 0.07 0.08]]
Wh:[[0.01 0.03 0.05 0.07]
 [0.02 0.04 0.06 0.08]
 [0.03 0.05 0.07 0.08]
 [0.04 0.06 0.08 0.1 ]]
H:[[0.79494228 0.81839002 0.83939649 0.85584174]]
h.shape(1, 4)


array([[0.79494228, 0.81839002, 0.83939649, 0.85584174]])