Week2授業前課題3 行列積のスクラッチ
---

問題1】行列積を手計算する
---
>AとBの行列積を手計算で解いてください。
計算過程もマークダウンテキストを用いて説明してください。
```
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
```

-1*0 + 2*0 + 3*2 = 6
-1*2 + 2*2 + 3*9 = 2
-1*1 + 2*-8 + 3*-1 = -20

4*0 + -5*0 + 6*2 = 12
4*2 + -5*2 + 6*9 = 52
4*1 + -5*-8 + 6*-1 = 38

7*0 + 8*0 + -9*2 = -18
7*2 + 8*2 + -9*9 = -51
7*1 + 8*-8 + -9*-1 = 48
```
[6 2 -20]
[12 52 38]
[-18 -51 80]
```


【問題2】NumPyの関数による計算
---
>この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。
これらを使い行列積を計算してください。
参考URL:
https://note.nkmk.me/python-numpy-matrix/

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [3]:
a_b_ndarray = np.matmul(a_ndarray, b_ndarray)
a_b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題3】ある要素の計算を実装
---
>手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。
参考URL: https://teratail.com/questions/196093
完全にチート

Σの計算をpythonで：
https://www.wantanblog.com/entry/2019/12/14/162806
```
import numpy as npy

# 関数k
def funck(k):
    return k

# 関数k^2
def funckk(k):
    return k**2

# 1から5の配列
numlist = [1,2,3,4,5]

resultk = 0
resultkk = 0

for i in numlist:
    resultk = resultk + funck(i)
    
for i in numlist:
    resultkk = resultkk + funckk(i)

print('kの和')
print(resultk)
print('k^2の和')
print(resultkk)
```

その他参考URL:ベクトル内積の計算for文
https://python-textbook.readthedocs.io/en/latest/src/tutorial2.html


In [7]:
def matrix_multiplication(U,V):
    answer=[]
    u_colmun_length=len(U[0])
    v_row_lengthh=len(V)
    v_column_length=len(V[0])
    #Uの列数とVの行数が同じじゃないなら計算できない
    if u_colmun_length != v_row_lengthh:
        print("Could not compute")
        return
    else:
        #Uの行列から１行を取り出す
        for u in U:
            temp=[]        
            colmun_index=0
            #Vの行列から一列を取り出す
            for _ in range(v_column_length):
                a = [x[colmun_index] for x in V]
                el_index=0         
                temp_multiple=0
                #Uの行とVの列を掛け算し足し合わせる
                for _ in range(u_colmun_length):   
                    temp_multiple+=u[el_index]*a[el_index] 
                    el_index+=1         
                #行列の行を作成
                temp.append(temp_multiple)                
                colmun_index+=1   
            #行を追加
            answer.append(temp)
    print(answer)

matrix_multiplication([[-1, 2, 3], [4, -5, 6], [7, 8, -9]],[[0, 2, 1], [0, 2, -8], [2, 9, -1]])    

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]
