Week2授業前課題3 行列積のスクラッチ
---

問題1】行列積を手計算する
---
>AとBの行列積を手計算で解いてください。
計算過程もマークダウンテキストを用いて説明してください。
```
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
```

-1*0 + 2*0 + 3*2 = 6
-1*2 + 2*2 + 3*9 = 2
-1*1 + 2*-8 + 3*-1 = -20

4*0 + -5*0 + 6*2 = 12
4*2 + -5*2 + 6*9 = 52
4*1 + -5*-8 + 6*-1 = 38

7*0 + 8*0 + -9*2 = -18
7*2 + 8*2 + -9*9 = -51
7*1 + 8*-8 + -9*-1 = 48
```
[6 2 -20]
[12 52 38]
[-18 -51 80]
```


【問題2】NumPyの関数による計算
---
>この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。
これらを使い行列積を計算してください。
参考URL:
https://note.nkmk.me/python-numpy-matrix/

In [56]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [57]:
a_b_ndarray = np.matmul(a_ndarray, b_ndarray)
a_b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題3】ある要素の計算を実装
---
>手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。
参考URL: https://teratail.com/questions/196093
完全にチート

Σの計算をpythonで：
https://www.wantanblog.com/entry/2019/12/14/162806
```
import numpy as npy

# 関数k
def funck(k):
    return k

# 関数k^2
def funckk(k):
    return k**2

# 1から5の配列
numlist = [1,2,3,4,5]

resultk = 0
resultkk = 0

for i in numlist:
    resultk = resultk + funck(i)
    
for i in numlist:
    resultkk = resultkk + funckk(i)

print('kの和')
print(resultk)
print('k^2の和')
print(resultkk)
```

その他参考URL:ベクトル内積の計算for文
https://python-textbook.readthedocs.io/en/latest/src/tutorial2.html


In [58]:
result = a_ndarray[0] * b_ndarray[:, 0]
result

result_calc = 0
for i in range(a_ndarray.shape[0]):
    result_calc+=a_ndarray[0,i] *  b_ndarray[i,0]
print(result_calc)

6


【問題4】行列積を行う関数の作成
---
>問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。
行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。
計算結果である 3×3の行列Cの各要素 ci,jは数式で表すと次のようになります。



In [59]:
def matrix_multiplication(a, b):
    c = np.empty((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i, j] = (a[i]*b[:, j]).sum()
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
matrix_multiplication(a_ndarray,b_ndarray) 


array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

【問題5】計算が定義されない入力を判定する
----
>問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。
if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [60]:
def matrix_multiplication_assart(a, b):
    assert a.shape[1] == b.shape[0]
    c = np.empty((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i, j] = (a[i]*b[:, j]).sum()
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
matrix_multiplication(a_ndarray,b_ndarray) 

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

【問題6】転置
----
>片方の行列を転置することで、行列積が計算できるようになります。

転置前は計算することができない。

In [61]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
c_ndarray = np.array([[0, 2, 1], [0, 2, -8]])
print('{}'.format(a_ndarray@c_ndarray))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

転置後は計算することができる。

In [62]:
print('{}'.format(a_ndarray@c_ndarray.T))

[[  7 -20]
 [ -4 -58]
 [  7  88]]
